/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.MethodParameterApiDescriptionModel
import com.mrdoggyapp.doggyapi.models.ParameterApiDescriptionModel
import com.mrdoggyapp.doggyapi.models.ReturnValueApiDescriptionModel

import com.squareup.moshi.Json

/**
 * 
 *
 * @param uniqueName 
 * @param name 
 * @param httpMethod 
 * @param url 
 * @param supportedVersions 
 * @param parametersOnMethod 
 * @param parameters 
 * @param returnValue 
 * @param allowAnonymous 
 * @param implementFrom 
 */

data class ActionApiDescriptionModel (

    @Json(name = "uniqueName")
    val uniqueName: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "httpMethod")
    val httpMethod: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "supportedVersions")
    val supportedVersions: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "parametersOnMethod")
    val parametersOnMethod: kotlin.collections.List<MethodParameterApiDescriptionModel>? = null,

    @Json(name = "parameters")
    val parameters: kotlin.collections.List<ParameterApiDescriptionModel>? = null,

    @Json(name = "returnValue")
    val returnValue: ReturnValueApiDescriptionModel? = null,

    @Json(name = "allowAnonymous")
    val allowAnonymous: kotlin.Boolean? = null,

    @Json(name = "implementFrom")
    val implementFrom: kotlin.String? = null

)

