/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.ApplicationAuthConfigurationDto
import com.mrdoggyapp.doggyapi.models.ApplicationFeatureConfigurationDto
import com.mrdoggyapp.doggyapi.models.ApplicationLocalizationConfigurationDto
import com.mrdoggyapp.doggyapi.models.ApplicationSettingConfigurationDto
import com.mrdoggyapp.doggyapi.models.ClockDto
import com.mrdoggyapp.doggyapi.models.CurrentTenantDto
import com.mrdoggyapp.doggyapi.models.CurrentUserDto
import com.mrdoggyapp.doggyapi.models.MultiTenancyInfoDto
import com.mrdoggyapp.doggyapi.models.ObjectExtensionsDto
import com.mrdoggyapp.doggyapi.models.TimingDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param localization 
 * @param auth 
 * @param setting 
 * @param currentUser 
 * @param features 
 * @param multiTenancy 
 * @param currentTenant 
 * @param timing 
 * @param clock 
 * @param objectExtensions 
 */

data class ApplicationConfigurationDto (

    @Json(name = "localization")
    val localization: ApplicationLocalizationConfigurationDto? = null,

    @Json(name = "auth")
    val auth: ApplicationAuthConfigurationDto? = null,

    @Json(name = "setting")
    val setting: ApplicationSettingConfigurationDto? = null,

    @Json(name = "currentUser")
    val currentUser: CurrentUserDto? = null,

    @Json(name = "features")
    val features: ApplicationFeatureConfigurationDto? = null,

    @Json(name = "multiTenancy")
    val multiTenancy: MultiTenancyInfoDto? = null,

    @Json(name = "currentTenant")
    val currentTenant: CurrentTenantDto? = null,

    @Json(name = "timing")
    val timing: TimingDto? = null,

    @Json(name = "clock")
    val clock: ClockDto? = null,

    @Json(name = "objectExtensions")
    val objectExtensions: ObjectExtensionsDto? = null

)

