/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.CurrentCultureDto
import com.mrdoggyapp.doggyapi.models.LanguageInfo
import com.mrdoggyapp.doggyapi.models.NameValue

import com.squareup.moshi.Json

/**
 * 
 *
 * @param propertyValues 
 * @param languages 
 * @param currentCulture 
 * @param defaultResourceName 
 * @param languagesMap 
 * @param languageFilesMap 
 */

data class ApplicationLocalizationConfigurationDto (

    @Json(name = "values")
    val propertyValues: kotlin.collections.Map<kotlin.String, kotlin.collections.Map<kotlin.String, kotlin.String>>? = null,

    @Json(name = "languages")
    val languages: kotlin.collections.List<LanguageInfo>? = null,

    @Json(name = "currentCulture")
    val currentCulture: CurrentCultureDto? = null,

    @Json(name = "defaultResourceName")
    val defaultResourceName: kotlin.String? = null,

    @Json(name = "languagesMap")
    val languagesMap: kotlin.collections.Map<kotlin.String, kotlin.collections.List<NameValue>>? = null,

    @Json(name = "languageFilesMap")
    val languageFilesMap: kotlin.collections.Map<kotlin.String, kotlin.collections.List<NameValue>>? = null

)

