/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.ModuleApiDescriptionModel
import com.mrdoggyapp.doggyapi.models.TypeApiDescriptionModel

import com.squareup.moshi.Json

/**
 * 
 *
 * @param modules 
 * @param types 
 */

data class ApplicationApiDescriptionModel (

    @Json(name = "modules")
    val modules: kotlin.collections.Map<kotlin.String, ModuleApiDescriptionModel>? = null,

    @Json(name = "types")
    val types: kotlin.collections.Map<kotlin.String, TypeApiDescriptionModel>? = null

)

