/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param policies 
 * @param grantedPolicies 
 */

data class ApplicationAuthConfigurationDto (

    @Json(name = "policies")
    val policies: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null,

    @Json(name = "grantedPolicies")
    val grantedPolicies: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null

)

