/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.ActionApiDescriptionModel
import com.mrdoggyapp.doggyapi.models.ControllerInterfaceApiDescriptionModel

import com.squareup.moshi.Json

/**
 * 
 *
 * @param controllerName 
 * @param controllerGroupName 
 * @param type 
 * @param interfaces 
 * @param actions 
 */

data class ControllerApiDescriptionModel (

    @Json(name = "controllerName")
    val controllerName: kotlin.String? = null,

    @Json(name = "controllerGroupName")
    val controllerGroupName: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "interfaces")
    val interfaces: kotlin.collections.List<ControllerInterfaceApiDescriptionModel>? = null,

    @Json(name = "actions")
    val actions: kotlin.collections.Map<kotlin.String, ActionApiDescriptionModel>? = null

)

