/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.DisplayStyle
import com.mrdoggyapp.doggyapi.models.ItemType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param description 
 * @param password 
 * @param parentItemId 
 * @param tagIds 
 * @param thumbId 
 * @param key 
 * @param md5 
 * @param contentType 
 * @param type 
 * @param displayStyle 
 * @param extension 
 * @param storageClass 
 * @param fileCreatedAt 
 * @param fileUpdatedAt 
 */

data class CreateUpdateItemDto (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "password")
    val password: kotlin.String? = null,

    @Json(name = "parentItemId")
    val parentItemId: java.util.UUID? = null,

    @Json(name = "tagIds")
    val tagIds: kotlin.collections.List<java.util.UUID>? = null,

    @Json(name = "thumbId")
    val thumbId: java.util.UUID? = null,

    @Json(name = "key")
    val key: kotlin.String? = null,

    @Json(name = "md5")
    val md5: kotlin.String? = null,

    @Json(name = "contentType")
    val contentType: kotlin.String? = null,

    @Json(name = "type")
    val type: ItemType? = null,

    @Json(name = "displayStyle")
    val displayStyle: DisplayStyle? = null,

    @Json(name = "extension")
    val extension: kotlin.String? = null,

    @Json(name = "storageClass")
    val storageClass: kotlin.String? = null,

    @Json(name = "fileCreatedAt")
    val fileCreatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "fileUpdatedAt")
    val fileUpdatedAt: java.time.OffsetDateTime? = null

)

