/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param isAuthenticated 
 * @param id 
 * @param tenantId 
 * @param impersonatorUserId 
 * @param impersonatorTenantId 
 * @param impersonatorUserName 
 * @param impersonatorTenantName 
 * @param userName 
 * @param name 
 * @param surName 
 * @param email 
 * @param emailVerified 
 * @param phoneNumber 
 * @param phoneNumberVerified 
 * @param roles 
 */

data class CurrentUserDto (

    @Json(name = "isAuthenticated")
    val isAuthenticated: kotlin.Boolean? = null,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "tenantId")
    val tenantId: java.util.UUID? = null,

    @Json(name = "impersonatorUserId")
    val impersonatorUserId: java.util.UUID? = null,

    @Json(name = "impersonatorTenantId")
    val impersonatorTenantId: java.util.UUID? = null,

    @Json(name = "impersonatorUserName")
    val impersonatorUserName: kotlin.String? = null,

    @Json(name = "impersonatorTenantName")
    val impersonatorTenantName: kotlin.String? = null,

    @Json(name = "userName")
    val userName: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "surName")
    val surName: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "emailVerified")
    val emailVerified: kotlin.Boolean? = null,

    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null,

    @Json(name = "phoneNumberVerified")
    val phoneNumberVerified: kotlin.Boolean? = null,

    @Json(name = "roles")
    val roles: kotlin.collections.List<kotlin.String>? = null

)

