/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param smtpHost 
 * @param smtpPort 
 * @param smtpUserName 
 * @param smtpPassword 
 * @param smtpDomain 
 * @param smtpEnableSsl 
 * @param smtpUseDefaultCredentials 
 * @param defaultFromAddress 
 * @param defaultFromDisplayName 
 */

data class EmailSettingsDto (

    @Json(name = "smtpHost")
    val smtpHost: kotlin.String? = null,

    @Json(name = "smtpPort")
    val smtpPort: kotlin.Int? = null,

    @Json(name = "smtpUserName")
    val smtpUserName: kotlin.String? = null,

    @Json(name = "smtpPassword")
    val smtpPassword: kotlin.String? = null,

    @Json(name = "smtpDomain")
    val smtpDomain: kotlin.String? = null,

    @Json(name = "smtpEnableSsl")
    val smtpEnableSsl: kotlin.Boolean? = null,

    @Json(name = "smtpUseDefaultCredentials")
    val smtpUseDefaultCredentials: kotlin.Boolean? = null,

    @Json(name = "defaultFromAddress")
    val defaultFromAddress: kotlin.String? = null,

    @Json(name = "defaultFromDisplayName")
    val defaultFromDisplayName: kotlin.String? = null

)

