/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.ExtensionPropertyUiFormDto
import com.mrdoggyapp.doggyapi.models.ExtensionPropertyUiLookupDto
import com.mrdoggyapp.doggyapi.models.ExtensionPropertyUiTableDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param onTable 
 * @param onCreateForm 
 * @param onEditForm 
 * @param lookup 
 */

data class ExtensionPropertyUiDto (

    @Json(name = "onTable")
    val onTable: ExtensionPropertyUiTableDto? = null,

    @Json(name = "onCreateForm")
    val onCreateForm: ExtensionPropertyUiFormDto? = null,

    @Json(name = "onEditForm")
    val onEditForm: ExtensionPropertyUiFormDto? = null,

    @Json(name = "lookup")
    val lookup: ExtensionPropertyUiLookupDto? = null

)

