/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param url 
 * @param resultListPropertyName 
 * @param displayPropertyName 
 * @param valuePropertyName 
 * @param filterParamName 
 */

data class ExtensionPropertyUiLookupDto (

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "resultListPropertyName")
    val resultListPropertyName: kotlin.String? = null,

    @Json(name = "displayPropertyName")
    val displayPropertyName: kotlin.String? = null,

    @Json(name = "valuePropertyName")
    val valuePropertyName: kotlin.String? = null,

    @Json(name = "filterParamName")
    val filterParamName: kotlin.String? = null

)

