/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.ExtensionPropertyApiDto
import com.mrdoggyapp.doggyapi.models.ExtensionPropertyAttributeDto
import com.mrdoggyapp.doggyapi.models.ExtensionPropertyUiDto
import com.mrdoggyapp.doggyapi.models.LocalizableStringDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 * @param typeSimple 
 * @param displayName 
 * @param api 
 * @param ui 
 * @param attributes 
 * @param configuration 
 * @param defaultValue 
 */

data class ExtensionPropertyDto (

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "typeSimple")
    val typeSimple: kotlin.String? = null,

    @Json(name = "displayName")
    val displayName: LocalizableStringDto? = null,

    @Json(name = "api")
    val api: ExtensionPropertyApiDto? = null,

    @Json(name = "ui")
    val ui: ExtensionPropertyUiDto? = null,

    @Json(name = "attributes")
    val attributes: kotlin.collections.List<ExtensionPropertyAttributeDto>? = null,

    @Json(name = "configuration")
    val configuration: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "defaultValue")
    val defaultValue: kotlin.Any? = null

)

