/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param typeSimple 
 * @param config 
 */

data class ExtensionPropertyAttributeDto (

    @Json(name = "typeSimple")
    val typeSimple: kotlin.String? = null,

    @Json(name = "config")
    val config: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

