/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.ExtensionPropertyApiCreateDto
import com.mrdoggyapp.doggyapi.models.ExtensionPropertyApiGetDto
import com.mrdoggyapp.doggyapi.models.ExtensionPropertyApiUpdateDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param onGet 
 * @param onCreate 
 * @param onUpdate 
 */

data class ExtensionPropertyApiDto (

    @Json(name = "onGet")
    val onGet: ExtensionPropertyApiGetDto? = null,

    @Json(name = "onCreate")
    val onCreate: ExtensionPropertyApiCreateDto? = null,

    @Json(name = "onUpdate")
    val onUpdate: ExtensionPropertyApiUpdateDto? = null

)

