/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.FeatureProviderDto
import com.mrdoggyapp.doggyapi.models.IStringValueType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param displayName 
 * @param `value` 
 * @param provider 
 * @param description 
 * @param valueType 
 * @param depth 
 * @param parentName 
 */

data class FeatureDto (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "value")
    val `value`: kotlin.String? = null,

    @Json(name = "provider")
    val provider: FeatureProviderDto? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "valueType")
    val valueType: IStringValueType? = null,

    @Json(name = "depth")
    val depth: kotlin.Int? = null,

    @Json(name = "parentName")
    val parentName: kotlin.String? = null

)

