/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.ItemDto
import com.mrdoggyapp.doggyapi.models.TagDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param creationTime 
 * @param creatorId 
 * @param lastModificationTime 
 * @param lastModifierId 
 * @param isDeleted 
 * @param deleterId 
 * @param deletionTime 
 * @param name 
 * @param key 
 * @param url 
 * @param propertySize 
 * @param md5 
 * @param contentType 
 * @param storageClass 
 * @param fileCreatedAt 
 * @param fileUpdatedAt 
 * @param fileId 
 * @param file 
 * @param folders 
 * @param tags 
 */

data class FileDto (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "creationTime")
    val creationTime: java.time.OffsetDateTime? = null,

    @Json(name = "creatorId")
    val creatorId: java.util.UUID? = null,

    @Json(name = "lastModificationTime")
    val lastModificationTime: java.time.OffsetDateTime? = null,

    @Json(name = "lastModifierId")
    val lastModifierId: java.util.UUID? = null,

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @Json(name = "deleterId")
    val deleterId: java.util.UUID? = null,

    @Json(name = "deletionTime")
    val deletionTime: java.time.OffsetDateTime? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "key")
    val key: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "size")
    val propertySize: kotlin.Int? = null,

    @Json(name = "md5")
    val md5: kotlin.String? = null,

    @Json(name = "contentType")
    val contentType: kotlin.String? = null,

    @Json(name = "storageClass")
    val storageClass: kotlin.String? = null,

    @Json(name = "fileCreatedAt")
    val fileCreatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "fileUpdatedAt")
    val fileUpdatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "fileId")
    val fileId: java.util.UUID? = null,

    @Json(name = "file")
    val file: FileDto? = null,

    @Json(name = "folders")
    val folders: kotlin.collections.List<ItemDto>? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<TagDto>? = null

)

