/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.PermissionGroupDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param entityDisplayName 
 * @param groups 
 */

data class GetPermissionListResultDto (

    @Json(name = "entityDisplayName")
    val entityDisplayName: kotlin.String? = null,

    @Json(name = "groups")
    val groups: kotlin.collections.List<PermissionGroupDto>? = null

)

