/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param extraProperties 
 * @param id 
 * @param creationTime 
 * @param creatorId 
 * @param lastModificationTime 
 * @param lastModifierId 
 * @param isDeleted 
 * @param deleterId 
 * @param deletionTime 
 * @param tenantId 
 * @param userName 
 * @param name 
 * @param surname 
 * @param email 
 * @param emailConfirmed 
 * @param phoneNumber 
 * @param phoneNumberConfirmed 
 * @param isActive 
 * @param lockoutEnabled 
 * @param lockoutEnd 
 * @param concurrencyStamp 
 */

data class IdentityUserDto (

    @Json(name = "extraProperties")
    val extraProperties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "creationTime")
    val creationTime: java.time.OffsetDateTime? = null,

    @Json(name = "creatorId")
    val creatorId: java.util.UUID? = null,

    @Json(name = "lastModificationTime")
    val lastModificationTime: java.time.OffsetDateTime? = null,

    @Json(name = "lastModifierId")
    val lastModifierId: java.util.UUID? = null,

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @Json(name = "deleterId")
    val deleterId: java.util.UUID? = null,

    @Json(name = "deletionTime")
    val deletionTime: java.time.OffsetDateTime? = null,

    @Json(name = "tenantId")
    val tenantId: java.util.UUID? = null,

    @Json(name = "userName")
    val userName: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "surname")
    val surname: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "emailConfirmed")
    val emailConfirmed: kotlin.Boolean? = null,

    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null,

    @Json(name = "phoneNumberConfirmed")
    val phoneNumberConfirmed: kotlin.Boolean? = null,

    @Json(name = "isActive")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "lockoutEnabled")
    val lockoutEnabled: kotlin.Boolean? = null,

    @Json(name = "lockoutEnd")
    val lockoutEnd: java.time.OffsetDateTime? = null,

    @Json(name = "concurrencyStamp")
    val concurrencyStamp: kotlin.String? = null

)

