/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param userName 
 * @param email 
 * @param password 
 * @param extraProperties 
 * @param name 
 * @param surname 
 * @param phoneNumber 
 * @param isActive 
 * @param lockoutEnabled 
 * @param roleNames 
 */

data class IdentityUserCreateDto (

    @Json(name = "userName")
    val userName: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "extraProperties")
    val extraProperties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "surname")
    val surname: kotlin.String? = null,

    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null,

    @Json(name = "isActive")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "lockoutEnabled")
    val lockoutEnabled: kotlin.Boolean? = null,

    @Json(name = "roleNames")
    val roleNames: kotlin.collections.List<kotlin.String>? = null

)

