/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.DisplayStyle
import com.mrdoggyapp.doggyapi.models.FileDto
import com.mrdoggyapp.doggyapi.models.ItemThumbDto
import com.mrdoggyapp.doggyapi.models.ItemType
import com.mrdoggyapp.doggyapi.models.TagDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param creationTime 
 * @param creatorId 
 * @param lastModificationTime 
 * @param lastModifierId 
 * @param isDeleted 
 * @param deleterId 
 * @param deletionTime 
 * @param name 
 * @param description 
 * @param totalCount 
 * @param password 
 * @param parentItemId 
 * @param thumbId 
 * @param thumb 
 * @param children 
 * @param tags 
 * @param key 
 * @param url 
 * @param propertySize 
 * @param md5 
 * @param contentType 
 * @param type 
 * @param displayStyle 
 * @param extension 
 * @param storageClass 
 * @param fileCreatedAt 
 * @param fileUpdatedAt 
 * @param fileId 
 * @param file 
 */

data class ItemDto (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "creationTime")
    val creationTime: java.time.OffsetDateTime? = null,

    @Json(name = "creatorId")
    val creatorId: java.util.UUID? = null,

    @Json(name = "lastModificationTime")
    val lastModificationTime: java.time.OffsetDateTime? = null,

    @Json(name = "lastModifierId")
    val lastModifierId: java.util.UUID? = null,

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @Json(name = "deleterId")
    val deleterId: java.util.UUID? = null,

    @Json(name = "deletionTime")
    val deletionTime: java.time.OffsetDateTime? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "totalCount")
    val totalCount: kotlin.Int? = null,

    @Json(name = "password")
    val password: kotlin.String? = null,

    @Json(name = "parentItemId")
    val parentItemId: java.util.UUID? = null,

    @Json(name = "thumbId")
    val thumbId: java.util.UUID? = null,

    @Json(name = "thumb")
    val thumb: ItemThumbDto? = null,

    @Json(name = "children")
    val children: kotlin.collections.List<ItemDto>? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<TagDto>? = null,

    @Json(name = "key")
    val key: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "size")
    val propertySize: kotlin.Int? = null,

    @Json(name = "md5")
    val md5: kotlin.String? = null,

    @Json(name = "contentType")
    val contentType: kotlin.String? = null,

    @Json(name = "type")
    val type: ItemType? = null,

    @Json(name = "displayStyle")
    val displayStyle: DisplayStyle? = null,

    @Json(name = "extension")
    val extension: kotlin.String? = null,

    @Json(name = "storageClass")
    val storageClass: kotlin.String? = null,

    @Json(name = "fileCreatedAt")
    val fileCreatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "fileUpdatedAt")
    val fileUpdatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "fileId")
    val fileId: java.util.UUID? = null,

    @Json(name = "file")
    val file: FileDto? = null

)

