/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param cultureName 
 * @param uiCultureName 
 * @param displayName 
 * @param flagIcon 
 */

data class LanguageInfo (

    @Json(name = "cultureName")
    val cultureName: kotlin.String? = null,

    @Json(name = "uiCultureName")
    val uiCultureName: kotlin.String? = null,

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "flagIcon")
    val flagIcon: kotlin.String? = null

)

