/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.ExtensionEnumDto
import com.mrdoggyapp.doggyapi.models.ModuleExtensionDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param modules 
 * @param enums 
 */

data class ObjectExtensionsDto (

    @Json(name = "modules")
    val modules: kotlin.collections.Map<kotlin.String, ModuleExtensionDto>? = null,

    @Json(name = "enums")
    val enums: kotlin.collections.Map<kotlin.String, ExtensionEnumDto>? = null

)

