/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param nameOnMethod 
 * @param name 
 * @param jsonName 
 * @param type 
 * @param typeSimple 
 * @param isOptional 
 * @param defaultValue 
 * @param constraintTypes 
 * @param bindingSourceId 
 * @param descriptorName 
 */

data class ParameterApiDescriptionModel (

    @Json(name = "nameOnMethod")
    val nameOnMethod: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "jsonName")
    val jsonName: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "typeSimple")
    val typeSimple: kotlin.String? = null,

    @Json(name = "isOptional")
    val isOptional: kotlin.Boolean? = null,

    @Json(name = "defaultValue")
    val defaultValue: kotlin.Any? = null,

    @Json(name = "constraintTypes")
    val constraintTypes: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "bindingSourceId")
    val bindingSourceId: kotlin.String? = null,

    @Json(name = "descriptorName")
    val descriptorName: kotlin.String? = null

)

