/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.PermissionGrantInfoDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param displayName 
 * @param permissions 
 */

data class PermissionGroupDto (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "permissions")
    val permissions: kotlin.collections.List<PermissionGrantInfoDto>? = null

)

