/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.ProviderInfoDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param displayName 
 * @param parentName 
 * @param isGranted 
 * @param allowedProviders 
 * @param grantedProviders 
 */

data class PermissionGrantInfoDto (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "parentName")
    val parentName: kotlin.String? = null,

    @Json(name = "isGranted")
    val isGranted: kotlin.Boolean? = null,

    @Json(name = "allowedProviders")
    val allowedProviders: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "grantedProviders")
    val grantedProviders: kotlin.collections.List<ProviderInfoDto>? = null

)

