/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param userName 
 * @param emailAddress 
 * @param password 
 * @param appName 
 * @param extraProperties 
 */

data class RegisterDto (

    @Json(name = "userName")
    val userName: kotlin.String,

    @Json(name = "emailAddress")
    val emailAddress: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "appName")
    val appName: kotlin.String,

    @Json(name = "extraProperties")
    val extraProperties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

