/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.RemoteServiceValidationErrorInfo

import com.squareup.moshi.Json

/**
 * 
 *
 * @param code 
 * @param message 
 * @param details 
 * @param `data` 
 * @param validationErrors 
 */

data class RemoteServiceErrorInfo (

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "details")
    val details: kotlin.String? = null,

    @Json(name = "data")
    val `data`: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "validationErrors")
    val validationErrors: kotlin.collections.List<RemoteServiceValidationErrorInfo>? = null

)

