/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param resetToken 
 * @param password 
 * @param userId 
 */

data class ResetPasswordDto (

    @Json(name = "resetToken")
    val resetToken: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "userId")
    val userId: java.util.UUID? = null

)

