/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param email 
 * @param appName 
 * @param returnUrl 
 * @param returnUrlHash 
 */

data class SendPasswordResetCodeDto (

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "appName")
    val appName: kotlin.String,

    @Json(name = "returnUrl")
    val returnUrl: kotlin.String? = null,

    @Json(name = "returnUrlHash")
    val returnUrlHash: kotlin.String? = null

)

