/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.IanaTimeZone
import com.mrdoggyapp.doggyapi.models.WindowsTimeZone

import com.squareup.moshi.Json

/**
 * 
 *
 * @param iana 
 * @param windows 
 */

data class TimeZone (

    @Json(name = "iana")
    val iana: IanaTimeZone? = null,

    @Json(name = "windows")
    val windows: WindowsTimeZone? = null

)

