/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models

import com.mrdoggyapp.doggyapi.models.PropertyApiDescriptionModel

import com.squareup.moshi.Json

/**
 * 
 *
 * @param baseType 
 * @param isEnum 
 * @param enumNames 
 * @param enumValues 
 * @param genericArguments 
 * @param properties 
 */

data class TypeApiDescriptionModel (

    @Json(name = "baseType")
    val baseType: kotlin.String? = null,

    @Json(name = "isEnum")
    val isEnum: kotlin.Boolean? = null,

    @Json(name = "enumNames")
    val enumNames: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "enumValues")
    val enumValues: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "genericArguments")
    val genericArguments: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "properties")
    val properties: kotlin.collections.List<PropertyApiDescriptionModel>? = null

)

