/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param userNameOrEmailAddress 
 * @param password 
 * @param rememberMe 
 */

data class UserLoginInfo (

    @Json(name = "userNameOrEmailAddress")
    val userNameOrEmailAddress: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "rememberMe")
    val rememberMe: kotlin.Boolean? = null

)

