/**
 * Doggy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mrdoggyapp.doggyapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param tenantId 
 * @param userName 
 * @param name 
 * @param surname 
 * @param email 
 * @param emailConfirmed 
 * @param phoneNumber 
 * @param phoneNumberConfirmed 
 */

data class UserData (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "tenantId")
    val tenantId: java.util.UUID? = null,

    @Json(name = "userName")
    val userName: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "surname")
    val surname: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "emailConfirmed")
    val emailConfirmed: kotlin.Boolean? = null,

    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null,

    @Json(name = "phoneNumberConfirmed")
    val phoneNumberConfirmed: kotlin.Boolean? = null

)

